// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSjm4uLYa-cj1b7KijNlqPxxfQo2COFmg',
    appId: '1:389292266861:web:3fdc1bbdd7e6c357b93664',
    messagingSenderId: '389292266861',
    projectId: 'sampleproject-e076a',
    authDomain: 'sampleproject-e076a.firebaseapp.com',
    storageBucket: 'sampleproject-e076a.firebasestorage.app',
    measurementId: 'G-EDW396G86W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgedl1CH9w36GBfvE_3yWLWp0kTVdDPvI',
    appId: '1:389292266861:android:09f9885f645614f3b93664',
    messagingSenderId: '389292266861',
    projectId: 'sampleproject-e076a',
    storageBucket: 'sampleproject-e076a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs6ZdCzu0DOvwt0wyvDPnijr2GcSI8Rlg',
    appId: '1:389292266861:ios:c9308408c82d8cd1b93664',
    messagingSenderId: '389292266861',
    projectId: 'sampleproject-e076a',
    storageBucket: 'sampleproject-e076a.firebasestorage.app',
    iosBundleId: 'com.example.mainProject',
  );
}
